# Generated by Django 5.1.2 on 2024-11-05 16:30

import django.contrib.gis.db.models.fields
from django.db import migrations
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):
    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='address',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0, 0), srid=4326),
            preserve_default=False,
        ),
    ]
