# Generated by Django 5.1.2 on 2024-11-06 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_property_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name_plural': 'properties'},
        ),
        migrations.AlterField(
            model_name='property',
            name='construction_year',
            field=models.PositiveIntegerField(help_text='Year of construction', validators=[django.core.validators.MaxValueValidator(2024), django.core.validators.MinValueValidator(1960)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='estimated_value',
            field=models.DecimalField(decimal_places=2, help_text='Estimated value of the property', max_digits=10),
        ),
        migrations.AlterField(
            model_name='property',
            name='square_footage',
            field=models.PositiveIntegerField(help_text='Square footage of the property'),
        ),
    ]
